version: '3'
services:
  site:
    image: mkramers-io-site
    ports:
      - "80:80"
      - "443:443"
      - "4000:4000"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
  api:
    image: mkramers-io-api
    ports:
      - "5000:5000"
